server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Rating
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: Rating-svc
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
