server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Hotel-svc
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

